name: Docker Image CI

on:
  push:
    branches: [ main ]
    
env:
  ECR_URI: ghcr.io/comroom-net/comroom_front
  REGISTRY: ghcr.io
  ORG: comroom-net

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker login
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.ORG }}
        password: ${{ secrets.CR_PAT }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag comroom-front:$(date +%s)
      
    - name: Push the image
      run: docker push $ECR_URI:$(docker images $ECR_URI --format "{{.Tag}}" | head -n 1)
